# Generated by Django 3.0.8 on 2020-07-09 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board_pin', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='board_pin',
            field=models.ManyToManyField(related_name='board_pin', through='board_pin.AccountBoardPin', to='board_pin.BoardPin'),
        ),
        migrations.AddField(
            model_name='account',
            name='comment',
            field=models.ManyToManyField(related_name='_account_comment_+', through='account.AccountCommentLike', to='account.Comment'),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Gender'),
        ),
        migrations.AddField(
            model_name='account',
            name='interest',
            field=models.ManyToManyField(related_name='interest', through='account.AccountInterest', to='account.Interest'),
        ),
        migrations.AddField(
            model_name='account',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Language'),
        ),
        migrations.AddField(
            model_name='account',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Region'),
        ),
        migrations.AddField(
            model_name='account',
            name='social_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SocialPlatform'),
        ),
    ]
