# Generated by Django 3.1a1 on 2020-07-17 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board_pin', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='board_pin',
            field=models.ManyToManyField(related_name='user', through='board_pin.AccountBoardPin', to='board_pin.BoardPin'),
        ),
        migrations.AddField(
            model_name='account',
            name='comment',
            field=models.ManyToManyField(related_name='user', through='account.AccountCommentLike', to='account.Comment'),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.gender'),
        ),
        migrations.AddField(
            model_name='account',
            name='interest',
            field=models.ManyToManyField(related_name='user', through='account.AccountInterest', to='account.Interest'),
        ),
        migrations.AddField(
            model_name='account',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.language'),
        ),
        migrations.AddField(
            model_name='account',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.region'),
        ),
        migrations.AddField(
            model_name='account',
            name='social_platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.socialplatform'),
        ),
    ]
