# Generated by Django 3.0.8 on 2020-07-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='image_url',
            field=models.URLField(max_length=300),
        ),
    ]
