# Generated by Django 3.0.8 on 2020-07-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_pin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='pin',
            name='detail',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='image_url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pin',
            name='link',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='title',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
